package com.makduck.dao;

import com.makduck.model.Inventory;
import com.makduck.model.InventoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    int countByExample(InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    int deleteByExample(InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    int deleteByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    int insert(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    int insertSelective(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    List<Inventory> selectByExample(InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    Inventory selectByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    int updateByExampleSelective(@Param("record") Inventory record, @Param("example") InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    int updateByExample(@Param("record") Inventory record, @Param("example") InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    int updateByPrimaryKeySelective(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    int updateByPrimaryKey(Inventory record);
}