package com.makduck.dao;

import com.makduck.model.Signon;
import com.makduck.model.SignonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SignonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    int countByExample(SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    int deleteByExample(SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    int insert(Signon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    int insertSelective(Signon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    List<Signon> selectByExample(SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    Signon selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    int updateByExampleSelective(@Param("record") Signon record, @Param("example") SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    int updateByExample(@Param("record") Signon record, @Param("example") SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    int updateByPrimaryKeySelective(Signon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signon
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    int updateByPrimaryKey(Signon record);
}