package com.makduck.model;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.userid
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.firstname
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.lastname
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.status
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.addr1
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String addr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.addr2
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String addr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.city
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.state
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.zip
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.country
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.phone
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.userid
     *
     * @return the value of account.userid
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.userid
     *
     * @param userid the value for account.userid
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email
     *
     * @return the value of account.email
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email
     *
     * @param email the value for account.email
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.firstname
     *
     * @return the value of account.firstname
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.firstname
     *
     * @param firstname the value for account.firstname
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.lastname
     *
     * @return the value of account.lastname
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.lastname
     *
     * @param lastname the value for account.lastname
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.status
     *
     * @return the value of account.status
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.status
     *
     * @param status the value for account.status
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.addr1
     *
     * @return the value of account.addr1
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.addr1
     *
     * @param addr1 the value for account.addr1
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setAddr1(String addr1) {
        this.addr1 = addr1 == null ? null : addr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.addr2
     *
     * @return the value of account.addr2
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.addr2
     *
     * @param addr2 the value for account.addr2
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.city
     *
     * @return the value of account.city
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.city
     *
     * @param city the value for account.city
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.state
     *
     * @return the value of account.state
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.state
     *
     * @param state the value for account.state
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.zip
     *
     * @return the value of account.zip
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.zip
     *
     * @param zip the value for account.zip
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.country
     *
     * @return the value of account.country
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.country
     *
     * @param country the value for account.country
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.phone
     *
     * @return the value of account.phone
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.phone
     *
     * @param phone the value for account.phone
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}