package com.makduck.model;

public class Inventory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.itemid
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private String itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.qty
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.itemid
     *
     * @return the value of inventory.itemid
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.itemid
     *
     * @param itemid the value for inventory.itemid
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.qty
     *
     * @return the value of inventory.qty
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.qty
     *
     * @param qty the value for inventory.qty
     *
     * @mbggenerated Fri Mar 28 14:52:57 KST 2014
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}