package com.makduck.model;

import java.math.BigDecimal;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemid
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private String itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.productid
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.listprice
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private BigDecimal listprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.unitcost
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private BigDecimal unitcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.supplier
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private Integer supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.status
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.attr1
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private String attr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.attr2
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private String attr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.attr3
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private String attr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.attr4
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private String attr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.attr5
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    private String attr5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemid
     *
     * @return the value of item.itemid
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemid
     *
     * @param itemid the value for item.itemid
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.productid
     *
     * @return the value of item.productid
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.productid
     *
     * @param productid the value for item.productid
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.listprice
     *
     * @return the value of item.listprice
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public BigDecimal getListprice() {
        return listprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.listprice
     *
     * @param listprice the value for item.listprice
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setListprice(BigDecimal listprice) {
        this.listprice = listprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.unitcost
     *
     * @return the value of item.unitcost
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public BigDecimal getUnitcost() {
        return unitcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.unitcost
     *
     * @param unitcost the value for item.unitcost
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setUnitcost(BigDecimal unitcost) {
        this.unitcost = unitcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.supplier
     *
     * @return the value of item.supplier
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public Integer getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.supplier
     *
     * @param supplier the value for item.supplier
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setSupplier(Integer supplier) {
        this.supplier = supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.status
     *
     * @return the value of item.status
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.status
     *
     * @param status the value for item.status
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.attr1
     *
     * @return the value of item.attr1
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.attr1
     *
     * @param attr1 the value for item.attr1
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1 == null ? null : attr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.attr2
     *
     * @return the value of item.attr2
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.attr2
     *
     * @param attr2 the value for item.attr2
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2 == null ? null : attr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.attr3
     *
     * @return the value of item.attr3
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.attr3
     *
     * @param attr3 the value for item.attr3
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3 == null ? null : attr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.attr4
     *
     * @return the value of item.attr4
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.attr4
     *
     * @param attr4 the value for item.attr4
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4 == null ? null : attr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.attr5
     *
     * @return the value of item.attr5
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.attr5
     *
     * @param attr5 the value for item.attr5
     *
     * @mbggenerated Fri Mar 28 15:17:47 KST 2014
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5 == null ? null : attr5.trim();
    }
}