package com.makduck.model;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productid
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.descn
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    private String descn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productid
     *
     * @return the value of product.productid
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productid
     *
     * @param productid the value for product.productid
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category
     *
     * @return the value of product.category
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category
     *
     * @param category the value for product.category
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.descn
     *
     * @return the value of product.descn
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.descn
     *
     * @param descn the value for product.descn
     *
     * @mbggenerated Fri Mar 28 14:31:58 KST 2014
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }
}