package com.makduck.model;

public class Signon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signon.username
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signon.password
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signon.username
     *
     * @return the value of signon.username
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signon.username
     *
     * @param username the value for signon.username
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signon.password
     *
     * @return the value of signon.password
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signon.password
     *
     * @param password the value for signon.password
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}