package com.makduck.model;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.suppid
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private Integer suppid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.name
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.status
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.addr1
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String addr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.addr2
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String addr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.city
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.state
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.zip
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.phone
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.suppid
     *
     * @return the value of supplier.suppid
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public Integer getSuppid() {
        return suppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.suppid
     *
     * @param suppid the value for supplier.suppid
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setSuppid(Integer suppid) {
        this.suppid = suppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.name
     *
     * @return the value of supplier.name
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.name
     *
     * @param name the value for supplier.name
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.status
     *
     * @return the value of supplier.status
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.status
     *
     * @param status the value for supplier.status
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.addr1
     *
     * @return the value of supplier.addr1
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.addr1
     *
     * @param addr1 the value for supplier.addr1
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setAddr1(String addr1) {
        this.addr1 = addr1 == null ? null : addr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.addr2
     *
     * @return the value of supplier.addr2
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.addr2
     *
     * @param addr2 the value for supplier.addr2
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.city
     *
     * @return the value of supplier.city
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.city
     *
     * @param city the value for supplier.city
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.state
     *
     * @return the value of supplier.state
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.state
     *
     * @param state the value for supplier.state
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.zip
     *
     * @return the value of supplier.zip
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.zip
     *
     * @param zip the value for supplier.zip
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.phone
     *
     * @return the value of supplier.phone
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.phone
     *
     * @param phone the value for supplier.phone
     *
     * @mbggenerated Fri Mar 28 14:55:30 KST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}